Feature/metadata raffle
poap-xyz/poap-fun pull request #65
Opened 2021-08-02 19:54 UTC by rlajous

## What's new?
- Added metadata for share links

## Changes include
- Added netlify function
- Added netlify redirect
- Added redirect from `:id` to `/fun/:id`

## Gif / Screenshots
![image](https://user-images.githubusercontent.com/40175251/127916026-93dde29f-db5a-4bff-ac50-7f80854a2cae.png)

2021-08-02 20:40 UTC, alavarello approved these changes
Great work!

2021-08-02 20:49 UTC, sebasfavaron requested changes

2021-08-02 20:49 UTC, sebasfavaron commented on frontend/netlify/functions/render.js
> +  console.log(agent, 'agent');
agent will never match bot 'W3C_Validator'

2021-08-03 13:20 UTC, sebasfavaron approved these changes

2021-08-10 17:08 UTC, merged